### ISSUE TITLE
Help to correct data errors

### ISSUE THREAD

**Issue by pwalsh** [okfn/tabular-validator-web#28]
Help section for each data error should be extendable by users (i.e.: crowdsourced) via an easy interface (i.e.: github editor over markdown files)
## Tasks
- [x] Add a help content folder to goodtables-web
- [x] each file in this folder corresponds with the ID of a result
- [x] each file in this folder editable via github editor
- [x] The main help page is auto generated from the list of available result types in goodtables. We now add the additional steps of:
  - [x] resolving a help text from the available markdown files
  - [x] Adding UI to encourage users to "edit this help section"

@rgrp I just realised a (big) disadvantage of having this data in the codebase: exposes code editing rights to anyone who we allow to edit the data. I know that the pull request pattern would negate this; not sure how easy that would be for non-tech users.

**Comment by rufuspollock** [comment]
@pwalsh i would go for request pattern - they just have to fork and then PR. I'd live with that for the time being - we can revisit if a problem.
